# Site settings
title: A New Chapter
header-img: img/home-bg.png
email: peggyleesix@gmail.com
copyright_name: pegsix
description: > # this means to ignore newlines until "baseurl:"
  Tech & Social Change
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pegsix
learn_profile: pegsix
email_username: peggyleesix@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
